export type Accent = "pink" | "cyan" | "gold";

export type ColorOption = { name: string; hex: string };

export type Product = {
  slug: string;
  name: string;
  category: CategorySlug;
  subtitle: string;
  description: string;
  price: number;
  mrp: number;
  images: [string, string];
  colors: ColorOption[];
  sizes: string[];
  rating: number;
  reviews: number;
  stock: number;
  badge: string | null;
  featured: boolean;
  accent: Accent;
};

export type CategorySlug = "men" | "women" | "kids" | "footwear" | "bags" | "home";

export const CATEGORY_LABELS: Record<CategorySlug, string> = {
  men: "Men",
  women: "Women",
  kids: "Kids",
  footwear: "Footwear",
  bags: "Bags",
  home: "Home",
};

export type Category = {
  slug: CategorySlug;
  name: string;
  tagline: string;
  count: number;
  image: string;
  accent: Accent;
  span: string;
};

export const CATEGORIES: Category[] = [
  {
    slug: "men",
    name: "Men",
    tagline: "Oversized tees, shirts & denim built for Siwan streets",
    count: 240,
    image: "/img/men-01.jpg",
    accent: "pink",
    span: "md:col-span-3 md:row-span-2",
  },
  {
    slug: "women",
    name: "Women",
    tagline: "Co-ords, kurtis & festive fits",
    count: 320,
    image: "/img/women-01.jpg",
    accent: "cyan",
    span: "md:col-span-3 md:row-span-2",
  },
  {
    slug: "kids",
    name: "Kids",
    tagline: "Playproof colours, ₹299 onwards",
    count: 150,
    image: "/img/kids-01.jpg",
    accent: "gold",
    span: "md:col-span-2",
  },
  {
    slug: "footwear",
    name: "Footwear",
    tagline: "Sneakers, sliders & school shoes",
    count: 180,
    image: "/img/footwear-01.jpg",
    accent: "cyan",
    span: "md:col-span-2",
  },
  {
    slug: "bags",
    name: "Bags",
    tagline: "Backpacks totes & travel",
    count: 90,
    image: "/img/bags-01.jpg",
    accent: "pink",
    span: "md:col-span-2",
  },
  {
    slug: "home",
    name: "Home",
    tagline: "Bedsheets, cushions & diwali decor",
    count: 120,
    image: "/img/home-01.jpg",
    accent: "gold",
    span: "md:col-span-6",
  },
];

const c = (name: string, hex: string): ColorOption => ({ name, hex });

export const PRODUCTS: Product[] = [
  {
    slug: "v-oversized-tee-black-pop",
    name: "Black Pop Oversized Tee",
    category: "men",
    subtitle: "240 GSM cotton · dropped shoulder",
    description:
      "Heavyweight cotton tee with a boxy dropped-shoulder cut and a high-density chest print. Pre-shrunk, breathes well in Bihar summers, holds shape after 30+ washes.",
    price: 599,
    mrp: 1299,
    images: ["/img/men-01.jpg", "/img/men-02.jpg"],
    colors: [c("Jet Black", "#111118"), c("Neon Pink", "#FF2E63"), c("Cyan Wash", "#08D9D6")],
    sizes: ["S", "M", "L", "XL", "XXL"],
    rating: 4.7,
    reviews: 218,
    stock: 26,
    badge: "Best Seller",
    featured: true,
    accent: "pink",
  },
  {
    slug: "v-charcoal-camp-shirt",
    name: "Charcoal Camp Shirt",
    category: "men",
    subtitle: "Relaxed fit · matte buttons",
    description:
      "A soft-touch camp collar shirt that works for college, chai runs and evening markets. Breathable viscose-blend weave with a subtle sheen under neon light.",
    price: 899,
    mrp: 1799,
    images: ["/img/men-02.jpg", "/img/men-01.jpg"],
    colors: [c("Charcoal", "#2B2B36"), c("Deep Teal", "#0E5A57")],
    sizes: ["S", "M", "L", "XL"],
    rating: 4.5,
    reviews: 96,
    stock: 14,
    badge: null,
    featured: true,
    accent: "cyan",
  },
  {
    slug: "v-street-cargo-jogger",
    name: "Street Cargo Jogger",
    category: "men",
    subtitle: "Ripstop · 6 pockets",
    description:
      "Light ripstop cargo jogger with articulated knees and a hidden zip pocket. Cut slim through the leg so it stacks clean over sneakers.",
    price: 1099,
    mrp: 1999,
    images: ["/img/men-01.jpg", "/img/footwear-02.jpg"],
    colors: [c("Jet Black", "#111118"), c("Sand", "#C6B79B")],
    sizes: ["28", "30", "32", "34", "36"],
    rating: 4.6,
    reviews: 143,
    stock: 9,
    badge: "New Drop",
    featured: true,
    accent: "gold",
  },
  {
    slug: "v-magenta-coord-set",
    name: "Magenta Co-ord Set",
    category: "women",
    subtitle: "Crop top + flowy palazzo",
    description:
      "Two-piece co-ord in a fluid crepe that moves with you. Elasticated waist, side pockets, and a dupatta-friendly silhouette for festive evenings.",
    price: 1299,
    mrp: 2499,
    images: ["/img/women-01.jpg", "/img/women-02.jpg"],
    colors: [c("Magenta", "#FF2E63"), c("Midnight", "#141426"), c("Cyan", "#08D9D6")],
    sizes: ["XS", "S", "M", "L", "XL"],
    rating: 4.8,
    reviews: 311,
    stock: 18,
    badge: "Trending",
    featured: true,
    accent: "pink",
  },
  {
    slug: "v-gold-thread-kurti",
    name: "Gold Thread Kurti",
    category: "women",
    subtitle: "Chanderi feel · side slit",
    description:
      "Straight-cut kurti with gold zari thread work along the placket and cuffs. Light enough for Chhath mornings, dressy enough for Diwali night.",
    price: 999,
    mrp: 1899,
    images: ["/img/women-02.jpg", "/img/women-01.jpg"],
    colors: [c("Blush", "#F2C4CE"), c("Mustard", "#FFC947"), c("Ink", "#171724")],
    sizes: ["XS", "S", "M", "L", "XL", "XXL"],
    rating: 4.6,
    reviews: 187,
    stock: 22,
    badge: "Festive",
    featured: true,
    accent: "gold",
  },
  {
    slug: "v-everyday-wide-leg",
    name: "Everyday Wide Leg Pant",
    category: "women",
    subtitle: "High rise · cotton twill",
    description:
      "High-rise wide leg with a pressed crease and a hidden hook closure. Structured twill that does not collapse by evening.",
    price: 849,
    mrp: 1699,
    images: ["/img/women-01.jpg", "/img/home-01.jpg"],
    colors: [c("Jet Black", "#111118"), c("Off White", "#EDE8DE")],
    sizes: ["XS", "S", "M", "L", "XL"],
    rating: 4.4,
    reviews: 74,
    stock: 11,
    badge: null,
    featured: false,
    accent: "cyan",
  },
  {
    slug: "v-kids-playproof-tee-set",
    name: "Kids Playproof Tee Set",
    category: "kids",
    subtitle: "Tee + shorts · ages 2–12",
    description:
      "Colour-locked cotton set with reinforced knees and a stretch waistband. Stain-release finish so Holi and maida handprints wash out.",
    price: 499,
    mrp: 999,
    images: ["/img/kids-01.jpg", "/img/women-02.jpg"],
    colors: [c("Cyan Pop", "#08D9D6"), c("Sunshine", "#FFC947"), c("Bubblegum", "#FF6B8F")],
    sizes: ["2-3Y", "4-5Y", "6-7Y", "8-9Y", "10-12Y"],
    rating: 4.8,
    reviews: 162,
    stock: 40,
    badge: "Parent Pick",
    featured: true,
    accent: "gold",
  },
  {
    slug: "v-kids-school-2piece",
    name: "School Ready 2-Piece",
    category: "kids",
    subtitle: "Uniform-tough poly-cotton",
    description:
      "Two shirts and one trouser bundle built for 200+ school days. Wrinkle resistant, colour-fast, and sized with growing room.",
    price: 799,
    mrp: 1499,
    images: ["/img/kids-01.jpg", "/img/men-02.jpg"],
    colors: [c("Sky", "#9FC9E8"), c("Jet Black", "#111118")],
    sizes: ["4-5Y", "6-7Y", "8-9Y", "10-12Y"],
    rating: 4.5,
    reviews: 88,
    stock: 25,
    badge: null,
    featured: false,
    accent: "cyan",
  },
  {
    slug: "v-pop-chunk-sneaker",
    name: "Pop Chunk Sneaker",
    category: "footwear",
    subtitle: "4cm platform · EVA sole",
    description:
      "Chunky low-top with a 4cm stacked EVA sole, breathable mesh lining and a grippy outsole that handles Siwan dust and monsoon pavement.",
    price: 1499,
    mrp: 2999,
    images: ["/img/footwear-01.jpg", "/img/footwear-02.jpg"],
    colors: [c("White / Pink", "#FF2E63"), c("White / Cyan", "#08D9D6")],
    sizes: ["UK 5", "UK 6", "UK 7", "UK 8", "UK 9", "UK 10"],
    rating: 4.7,
    reviews: 402,
    stock: 12,
    badge: "Hot 🔥",
    featured: true,
    accent: "pink",
  },
  {
    slug: "v-navy-runner-pro",
    name: "Navy Runner Pro",
    category: "footwear",
    subtitle: "Everyday cushion running",
    description:
      "Lightweight runner with a responsive midsole and a padded heel collar. Built for long days on your feet, from the shop to the station.",
    price: 1599,
    mrp: 2799,
    images: ["/img/footwear-02.jpg", "/img/footwear-01.jpg"],
    colors: [c("Navy / Gold", "#1B2A4A"), c("Black", "#111118")],
    sizes: ["UK 5", "UK 6", "UK 7", "UK 8", "UK 9"],
    rating: 4.6,
    reviews: 156,
    stock: 7,
    badge: "New Drop",
    featured: true,
    accent: "cyan",
  },
  {
    slug: "v-monsoon-slider",
    name: "Monsoon Slider",
    category: "footwear",
    subtitle: "Anti-slip · quick dry",
    description:
      "Contoured footbed slider with deep anti-skip grooves. Dries in minutes, soaks up nothing.",
    price: 399,
    mrp: 799,
    images: ["/img/footwear-01.jpg", "/img/kids-01.jpg"],
    colors: [c("Jet Black", "#111118"), c("Cyan", "#08D9D6")],
    sizes: ["UK 5", "UK 6", "UK 7", "UK 8", "UK 9"],
    rating: 4.3,
    reviews: 63,
    stock: 34,
    badge: null,
    featured: false,
    accent: "gold",
  },
  {
    slug: "v-tech-backpack-25l",
    name: "Tech Backpack 25L",
    category: "bags",
    subtitle: "Padded 15.6\" laptop bay",
    description:
      "Water-repellent shell, hideaway rain cover, USB pass-through and a false-bottom pocket. Sized for college, gym and a weekend train ride.",
    price: 1199,
    mrp: 2299,
    images: ["/img/bags-01.jpg", "/img/footwear-02.jpg"],
    colors: [c("Matte Black", "#111118"), c("Ink / Cyan", "#08D9D6")],
    sizes: ["One Size"],
    rating: 4.7,
    reviews: 209,
    stock: 16,
    badge: "Best Seller",
    featured: true,
    accent: "cyan",
  },
  {
    slug: "v-market-tote-tan",
    name: "Market Tote Tan",
    category: "bags",
    subtitle: "Vegan leather · boxed base",
    description:
      "Structured tote with a boxed base, magnetic closure and an inner zip pocket. Carries a laptop, a tiffin and a kilo of tamatar.",
    price: 899,
    mrp: 1699,
    images: ["/img/bags-01.jpg", "/img/women-02.jpg"],
    colors: [c("Tan", "#B98A5A"), c("Jet Black", "#111118")],
    sizes: ["One Size"],
    rating: 4.5,
    reviews: 77,
    stock: 20,
    badge: null,
    featured: false,
    accent: "gold",
  },
  {
    slug: "v-sling-crossbody",
    name: "Neon Sling Crossbody",
    category: "bags",
    subtitle: "Anti-theft back panel",
    description:
      "Compact sling with a hidden back slot for your phone and UPI card. Adjustable webbing that fits over a bulky jacket.",
    price: 499,
    mrp: 999,
    images: ["/img/bags-01.jpg", "/img/men-01.jpg"],
    colors: [c("Neon Pink", "#FF2E63"), c("Cyan", "#08D9D6"), c("Black", "#111118")],
    sizes: ["One Size"],
    rating: 4.4,
    reviews: 118,
    stock: 28,
    badge: "₹499 Steal",
    featured: true,
    accent: "pink",
  },
  {
    slug: "v-teal-bedsheet-set",
    name: "Teal Bedsheet Set",
    category: "home",
    subtitle: "144 TC · king + 2 covers",
    description:
      "Pure cotton percale set that stays cool through May. Faded-wash teal with a mustard border, king size with two pillow covers.",
    price: 899,
    mrp: 1799,
    images: ["/img/home-01.jpg", "/img/women-02.jpg"],
    colors: [c("Deep Teal", "#0E5A57"), c("Mustard", "#FFC947")],
    sizes: ["Single", "Double", "King"],
    rating: 4.6,
    reviews: 134,
    stock: 19,
    badge: "Home Hero",
    featured: true,
    accent: "gold",
  },
  {
    slug: "v-festive-cushion-trio",
    name: "Festive Cushion Trio",
    category: "home",
    subtitle: "16\" · zari + mirror work",
    description:
      "Set of three cushion covers with zari piping and mirror work. Filler pads included, ready for Diwali guests in five minutes.",
    price: 599,
    mrp: 1299,
    images: ["/img/home-01.jpg", "/img/kids-01.jpg"],
    colors: [c("Gold", "#FFC947"), c("Magenta", "#FF2E63")],
    sizes: ["16 inch", "18 inch"],
    rating: 4.5,
    reviews: 61,
    stock: 30,
    badge: "Diwali Edit",
    featured: true,
    accent: "pink",
  },
  {
    slug: "v-brushed-throw-blanket",
    name: "Brushed Throw Blanket",
    category: "home",
    subtitle: "Winter-weight · 150x200",
    description:
      "Brushed microfibre throw for Chhath-season nights on the roof. Reversible, anti-pill, machine washable.",
    price: 999,
    mrp: 1899,
    images: ["/img/home-01.jpg", "/img/men-02.jpg"],
    colors: [c("Ink", "#171724"), c("Wine", "#5C1130")],
    sizes: ["One Size"],
    rating: 4.4,
    reviews: 42,
    stock: 13,
    badge: null,
    featured: false,
    accent: "cyan",
  },
  {
    slug: "v-thermal-henley",
    name: "Thermal Henley",
    category: "men",
    subtitle: "Brushed inner · 4 buttons",
    description:
      "Slim thermal henley that layers under a jacket or wears alone. Brushed inside, smooth outside, zero itch.",
    price: 699,
    mrp: 1399,
    images: ["/img/men-02.jpg", "/img/men-01.jpg"],
    colors: [c("Jet Black", "#111118"), c("Charcoal", "#2B2B36")],
    sizes: ["S", "M", "L", "XL"],
    rating: 4.5,
    reviews: 59,
    stock: 21,
    badge: null,
    featured: false,
    accent: "cyan",
  },
  {
    slug: "v-washed-denim-jacket",
    name: "Washed Denim Jacket",
    category: "men",
    subtitle: "Mid-wash · brushed lining",
    description:
      "Rigid-then-soft denim jacket with a mid indigo wash, brushed lining for winter mornings and deep chest pockets.",
    price: 1899,
    mrp: 3499,
    images: ["/img/men-02.jpg", "/img/men-01.jpg"],
    colors: [c("Mid Indigo", "#3A5A8C"), c("Jet Black", "#111118")],
    sizes: ["S", "M", "L", "XL"],
    rating: 4.7,
    reviews: 88,
    stock: 6,
    badge: "Winter Drop",
    featured: true,
    accent: "cyan",
  },
  {
    slug: "v-varsity-tee-white",
    name: "Varsity Tee White",
    category: "men",
    subtitle: "Contrast sleeve · 220 GSM",
    description:
      "Clean white base with contrast raglan sleeves and a puff-print varsity number. A quiet flex that works with anything.",
    price: 549,
    mrp: 1199,
    images: ["/img/men-01.jpg", "/img/kids-01.jpg"],
    colors: [c("Off White", "#EDE8DE"), c("Jet Black", "#111118")],
    sizes: ["S", "M", "L", "XL", "XXL"],
    rating: 4.4,
    reviews: 121,
    stock: 31,
    badge: null,
    featured: false,
    accent: "pink",
  },
  {
    slug: "v-chikankari-kurti-white",
    name: "Chikankari White Kurti",
    category: "women",
    subtitle: "Hand-feel embroidery · A-line",
    description:
      "A-line cotton kurti with tonal chikankari work along the yoke. Breathable enough for a full day of running around.",
    price: 1099,
    mrp: 2199,
    images: ["/img/women-02.jpg", "/img/women-01.jpg"],
    colors: [c("Off White", "#EDE8DE"), c("Powder Blue", "#BBD3EA")],
    sizes: ["XS", "S", "M", "L", "XL", "XXL"],
    rating: 4.8,
    reviews: 264,
    stock: 15,
    badge: "Trending",
    featured: true,
    accent: "cyan",
  },
  {
    slug: "v-denim-wide-cargo",
    name: "Denim Wide Cargo",
    category: "women",
    subtitle: "High rise · stretch denim",
    description:
      "Wide-leg cargo in stretch denim that keeps its shape. Elastic-back waistband, eight pockets, zero sagging.",
    price: 1399,
    mrp: 2599,
    images: ["/img/women-01.jpg", "/img/men-02.jpg"],
    colors: [c("Mid Indigo", "#3A5A8C"), c("Jet Black", "#111118")],
    sizes: ["XS", "S", "M", "L", "XL"],
    rating: 4.5,
    reviews: 97,
    stock: 8,
    badge: "New Drop",
    featured: true,
    accent: "pink",
  },
  {
    slug: "v-festive-bandhani-dupatta",
    name: "Bandhani Dupatta",
    category: "women",
    subtitle: "Tie-dye · gota border",
    description:
      "Light georgette bandhani dupatta with a gota lace border. Instantly upgrades a plain kurta for Chhath visits.",
    price: 399,
    mrp: 899,
    images: ["/img/women-02.jpg", "/img/home-01.jpg"],
    colors: [c("Magenta", "#FF2E63"), c("Mustard", "#FFC947"), c("Ink", "#171724")],
    sizes: ["One Size"],
    rating: 4.6,
    reviews: 143,
    stock: 44,
    badge: "₹399 Steal",
    featured: false,
    accent: "gold",
  },
  {
    slug: "v-kids-hoodie-bright",
    name: "Kids Bright Hoodie",
    category: "kids",
    subtitle: "Fleece-lined · ages 3–12",
    description:
      "Brushed-fleece hoodie with a kangaroo pocket and reflective print for early winter school walks.",
    price: 699,
    mrp: 1399,
    images: ["/img/kids-01.jpg", "/img/men-01.jpg"],
    colors: [c("Cyan Pop", "#08D9D6"), c("Bubblegum", "#FF6B8F"), c("Jet Black", "#111118")],
    sizes: ["3-4Y", "5-6Y", "7-8Y", "9-10Y", "11-12Y"],
    rating: 4.7,
    reviews: 108,
    stock: 23,
    badge: "Winter Drop",
    featured: true,
    accent: "cyan",
  },
  {
    slug: "v-court-sneaker-white",
    name: "Court Sneaker White",
    category: "footwear",
    subtitle: "Low profile · cupsole",
    description:
      "Minimal leather-look court sneaker on a stitched cupsole. Goes with jeans, kurta-pajama and everything between.",
    price: 1299,
    mrp: 2499,
    images: ["/img/footwear-02.jpg", "/img/footwear-01.jpg"],
    colors: [c("Off White", "#EDE8DE"), c("Jet Black", "#111118")],
    sizes: ["UK 5", "UK 6", "UK 7", "UK 8", "UK 9", "UK 10"],
    rating: 4.6,
    reviews: 231,
    stock: 17,
    badge: "Best Seller",
    featured: true,
    accent: "gold",
  },
  {
    slug: "v-school-black-shoes",
    name: "School Black Shoes",
    category: "footwear",
    subtitle: "Polishable · scuff guard",
    description:
      "Everyday black school shoes with a scuff-guard toe bumper and a cushioned insole that survives a full term.",
    price: 799,
    mrp: 1499,
    images: ["/img/footwear-02.jpg", "/img/kids-01.jpg"],
    colors: [c("Jet Black", "#111118")],
    sizes: ["UK 10", "UK 11", "UK 12", "UK 13", "UK 1", "UK 2"],
    rating: 4.4,
    reviews: 76,
    stock: 36,
    badge: "Term Ready",
    featured: false,
    accent: "cyan",
  },
  {
    slug: "v-travel-duffel-38l",
    name: "Travel Duffel 38L",
    category: "bags",
    subtitle: "Shoe tunnel · trolley sleeve",
    description:
      "Weekend duffel with a ventilated shoe tunnel, trolley pass-through and a wet pocket for monsoon gear.",
    price: 1699,
    mrp: 3199,
    images: ["/img/bags-01.jpg", "/img/home-01.jpg"],
    colors: [c("Matte Black", "#111118"), c("Sand", "#C6B79B")],
    sizes: ["One Size"],
    rating: 4.6,
    reviews: 64,
    stock: 9,
    badge: "New Drop",
    featured: true,
    accent: "gold",
  },
  {
    slug: "v-laptop-sleeve-slim",
    name: "Neon Laptop Sleeve",
    category: "bags",
    subtitle: "14\" & 15.6\" · water repel",
    description:
      "Slim padded sleeve with a neon zip pull and a hidden AirTag-style card slot. Fits inside the 25L backpack.",
    price: 449,
    mrp: 999,
    images: ["/img/bags-01.jpg", "/img/men-02.jpg"],
    colors: [c("Neon Pink", "#FF2E63"), c("Cyan", "#08D9D6"), c("Jet Black", "#111118")],
    sizes: ["14 inch", "15.6 inch"],
    rating: 4.3,
    reviews: 52,
    stock: 27,
    badge: "₹449 Steal",
    featured: false,
    accent: "pink",
  },
  {
    slug: "v-mustard-bedsheet-set",
    name: "Mustard Bedsheet Set",
    category: "home",
    subtitle: "144 TC · double + 2 covers",
    description:
      "Colour-fast mustard percale with a block-print border. Double size with two matching pillow covers.",
    price: 749,
    mrp: 1599,
    images: ["/img/home-01.jpg", "/img/women-02.jpg"],
    colors: [c("Mustard", "#FFC947"), c("Deep Teal", "#0E5A57")],
    sizes: ["Single", "Double", "King"],
    rating: 4.5,
    reviews: 89,
    stock: 26,
    badge: null,
    featured: false,
    accent: "gold",
  },
  {
    slug: "v-diwali-lantern-set",
    name: "Diwali Lantern Set",
    category: "home",
    subtitle: "Pack of 5 · foldable",
    description:
      "Five foldable lanterns in graded neon tones with LED inserts. Sets up on a balcony in under five minutes.",
    price: 599,
    mrp: 1299,
    images: ["/img/home-01.jpg", "/img/kids-01.jpg"],
    colors: [c("Gold Mix", "#FFC947"), c("Neon Mix", "#FF2E63")],
    sizes: ["One Size"],
    rating: 4.7,
    reviews: 71,
    stock: 33,
    badge: "Diwali Edit",
    featured: true,
    accent: "pink",
  },
  {
    slug: "v-bath-towel-set-4",
    name: "Cotton Towel Set (4)",
    category: "home",
    subtitle: "500 GSM · quick dry",
    description:
      "Two bath towels and two hand towels in 500 GSM combed cotton. Lint-free after the second wash.",
    price: 899,
    mrp: 1799,
    images: ["/img/home-01.jpg", "/img/men-02.jpg"],
    colors: [c("Deep Teal", "#0E5A57"), c("Blush", "#F2C4CE"), c("Ink", "#171724")],
    sizes: ["One Size"],
    rating: 4.4,
    reviews: 58,
    stock: 21,
    badge: null,
    featured: false,
    accent: "cyan",
  },
];

export type Testimonial = {
  id: number;
  name: string;
  city: string;
  rating: number;
  quote: string;
  purchase: string;
  accent: Accent;
};

export const TESTIMONIALS: Testimonial[] = [
  {
    id: 1,
    name: "Aman Kumar",
    city: "Siwan, Gopalganj Road",
    rating: 5,
    quote:
      "Bhai sneaker quality dekh ke shock ho gaya — ₹1499 me yahi jo Patna me ₹3500 ka milta hai. Store pe try kiya, wahi le aaya. 🔥",
    purchase: "Pop Chunk Sneaker",
    accent: "pink",
  },
  {
    id: 2,
    name: "Priya Sinha",
    city: "Mairwa",
    rating: 5,
    quote:
      "Ordered the co-ord on WhatsApp, pickup ready in 2 hours. Stitching is solid, colour exactly like the photos.",
    purchase: "Magenta Co-ord Set",
    accent: "cyan",
  },
  {
    id: 3,
    name: "Rahul Verma",
    city: "Siwan College Road",
    rating: 4,
    quote:
      "Oversized tee is actually oversized, not 'Chinese medium'. 3 wash ho gaye, print ekdum tight hai.",
    purchase: "Black Pop Oversized Tee",
    accent: "gold",
  },
  {
    id: 4,
    name: "Nisha Gupta",
    city: "Bagha",
    rating: 5,
    quote:
      "Kurti Diwali ke liye li thi — sabko laga boutique se hai. Gold work really pops in photos.",
    purchase: "Gold Thread Kurti",
    accent: "gold",
  },
  {
    id: 5,
    name: "Sunny Ali",
    city: "Maharajganj",
    rating: 5,
    quote:
      "Backpack 25L is the real deal. Rain cover bhi hai, laptop bhi safe. College ke liye best.",
    purchase: "Tech Backpack 25L",
    accent: "cyan",
  },
  {
    id: 6,
    name: "Rekha Devi",
    city: "Siwan, Station Road",
    rating: 5,
    quote:
      "Bachchon ke clothes yahin se leti hoon — 2 set ₹999. Do mahine chale gaye, colour nahi gaya.",
    purchase: "Kids Playproof Tee Set",
    accent: "pink",
  },
];

export const MARQUEE_ITEMS = [
  "NEW DROPS EVERY FRIDAY",
  "FREE STORE PICKUP",
  "UPI ACCEPTED",
  "SIWAN'S #1 STYLE STORE",
  "TRY IN-STORE, THEN BUY",
  "FLAT 10% OFF WITH SIWAN10",
];

/** Real size charts used by the PDP size-guide modal. */
type SizeTable = { title: string; head: string[]; rows: string[][] };

export const SIZE_GUIDES: Record<"men" | "women" | "kids" | "footwear" | "bags" | "home", SizeTable> = {
  men: {
    title: "Men · tops & shirts",
    head: ["Size", "Chest", "Length", "Shoulder"],
    rows: [
      ["S", "38\"", "27\"", "17\""],
      ["M", "40\"", "28\"", "17.5\""],
      ["L", "42\"", "29\"", "18\""],
      ["XL", "44\"", "30\"", "18.5\""],
      ["XXL", "46\"", "31\"", "19\""],
    ],
  },
  women: {
    title: "Women · kurtis & co-ords",
    head: ["Size", "Bust", "Waist", "Kurti length"],
    rows: [
      ["XS", "32\"", "26\"", "40\""],
      ["S", "34\"", "28\"", "41\""],
      ["M", "36\"", "30\"", "42\""],
      ["L", "38\"", "32\"", "43\""],
      ["XL", "40\"", "34\"", "44\""],
      ["XXL", "42\"", "36\"", "45\""],
    ],
  },
  kids: {
    title: "Kids · sets & school wear",
    head: ["Size", "Age", "Chest", "Length"],
    rows: [
      ["2-3Y", "2–3 yrs", "22\"", "15\""],
      ["4-5Y", "4–5 yrs", "24\"", "17\""],
      ["6-7Y", "6–7 yrs", "26\"", "19\""],
      ["8-9Y", "8–9 yrs", "28\"", "21\""],
      ["10-12Y", "10–12 yrs", "30\"", "23\""],
    ],
  },
  footwear: {
    title: "Footwear · UK sizes",
    head: ["UK size", "Foot length (cm)", "Insole (cm)"],
    rows: [
      ["UK 5", "23.5", "24.0"],
      ["UK 6", "24.5", "25.0"],
      ["UK 7", "25.3", "25.8"],
      ["UK 8", "26.1", "26.6"],
      ["UK 9", "26.9", "27.4"],
      ["UK 10", "27.8", "28.3"],
    ],
  },
  bags: {
    title: "Bags · capacity & fit",
    head: ["Bag", "Volume", "Laptop", "Weight"],
    rows: [
      ["Sling", "3L", "—", "0.3 kg"],
      ["Tote", "14L", "13\"", "0.6 kg"],
      ["Backpack 25L", "25L", "15.6\"", "0.9 kg"],
      ["Travel 38L", "38L", "17\"", "1.3 kg"],
    ],
  },
  home: {
    title: "Home · bedsheets & covers",
    head: ["Size", "Bedsheet", "Fits mattress", "Pillow covers"],
    rows: [
      ["Single", "60 x 90\"", "39 x 75\"", "1"],
      ["Double", "78 x 90\"", "54 x 75\"", "2"],
      ["King", "90 x 108\"", "72 x 78\"", "2"],
    ],
  },
};

/** Order lifecycle used by the tracking page and admin console. */
export const ORDER_STATUSES = ["new", "packed", "ready", "completed", "cancelled"] as const;
export type OrderStatus = (typeof ORDER_STATUSES)[number];

export const ORDER_STATUS_META: Record<OrderStatus, { label: string; hint: string; color: string }> = {
  new: { label: "Order placed", hint: "We've received it and are checking stock.", color: "#08D9D6" },
  packed: { label: "Packed", hint: "Folded, bagged and labelled with your name.", color: "#FFC947" },
  ready: { label: "Ready", hint: "Waiting at the counter or with the delivery partner.", color: "#FF2E63" },
  completed: { label: "Completed", hint: "Collected / delivered. Enjoy the fit!", color: "#4ADE80" },
  cancelled: { label: "Cancelled", hint: "Cancelled on request — nothing was charged.", color: "#A9ADBF" },
};

/** Store details — placeholders kept verbatim per brief. */
export const STORE = {
  name: "V-STYLE Siwan",
  address: "[STORE_ADDRESS]",
  phone: "[STORE_PHONE]",
  hours: "[STORE_HOURS]",
  whatsapp: "[WHATSAPP_NUMBER]",
  mapUrl: "https://maps.google.com/?q=Siwan+Bihar+India",
};
